version: "3"
services:
  datagenerationservice:
    image: datagenerationservice
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/datagenerationservice
    ports:
      - 8080:8080
    expose:
      - "8080"
volumes:
  data-volume: